### ISSUE TITLE
New control option `hideWhenEmbedded` for all controls

### ISSUE THREAD

**Issue by MattiasSp** [origo-map/origo-documentation#118]
The new control option `hideWhenEmbedded` works for all controls as per origo [PR#1095](https://github.com/origo-map/origo/pull/1095) and [PR#1115](https://github.com/origo-map/origo/pull/1115).

When adding docs for such options, should it be described in a separate section for common control options, on each control or both?

**Comment by jokd** [comment]
I suggest adding it for each control to be clear. May be overlooked otherwise.
Other opinions?

**Comment by jokd** [comment]
Fixed with e5d4a0a632f89ab9922001534c0e7d5cf6ec2fef
