### ISSUE TITLE
featureinfoOptions examples layout

### ISSUE THREAD

**Issue by mulfvik** [origo-map/origo-documentation#193]
This looks a bit weird, dont know if it is deliberate?

![image](https://user-images.githubusercontent.com/24228538/154031395-dfccc4bc-ea3b-4522-b01d-3bf2adae600d.png)

**Comment by asemoller** [comment]
Oh no... 

I guess something doesn't like five of # before the title, or is it something else?

**Comment by asemoller** [comment]
But it looks good in content > settings.md though:

![image](https://user-images.githubusercontent.com/17123002/154039289-dee3600f-ab1f-41ba-b29c-9c2fbc017769.png)

**Comment by mulfvik** [comment]
Oh, that looks better

**Comment by jokd** [comment]
Fixed
